apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: foos.test.io
spec:
  conversion:
    strategy: None
  group: test.io
  names:
    kind: Foo
    listKind: FooList
    plural: foos
    singular: foo
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              checksum:
                nullable: true
                type: string
              source:
                nullable: true
                type: string
            type: object
        type: object
    served: true
    storage: true
